### ISSUE TITLE
Additional mousetrap forks

### ISSUE THREAD

**Issue by lextiz** [mousetrap-js/mousetrap#8]
Hello @robincafolla,

As far as I understand this fork was created as last possible measure to have maintained version of mousetrap. Assuming @ccampbell will not become active and will not add contributors to original mousetrap repository, this is very logical. Did you consider contributing to more popular fork https://github.com/PolicyStat/combokeys instead of creating a new one?

**Comment by kafeltz** [comment]
hi, 
did you take a look [here](https://github.com/mousetrap-js/mousetrap/issues/2)?

**Comment by lextiz** [comment]
Yes, I have read this thread. How does it contradict with my question?

**Comment by robincafolla** [comment]
@lextiz I wasn't aware of the fork. Is it still actively maintained? It seems not to have had any recent activity. They seem to have closed a few issues, but nowhere near all of them.

**Comment by robincafolla** [comment]
I've posted on the repo to see if it's still maintained.

PolicyStat/combokeys/issues/45

**Comment by robincafolla** [comment]
It appears that the [combokeys](https://github.com/PolicyStat/combokeys) repo is not actively maintained, or at least their maintenance is even less frequent than my own.

I've opened https://github.com/mousetrap-js/mousetrap/issues/9 to merge their changes into our code-base.

I'm closing this issue for now.
